-- BASELINE — DDL de las 5 tablas heredadas del proyecto `lineup-argentina` que NO tenían migración de
-- creación en este repo (djve, lineup, cbot_cierres, pizarra_historico, compras). Dumpeado de la base
-- viva el 21/07/2026 (auditoría E1, hallazgo #5). Ver docs/auditoria/E1-datos.md, Anexo A.
--
-- Propósito: versionar el esquema que ya existe para que sea reproducible desde cero (clon / entorno
-- nuevo). Es IDEMPOTENTE (IF NOT EXISTS + guards) → aplicarla sobre la base actual es un no-op seguro.
-- Timestamp 0 a propósito: precede a todas las migraciones reales, que sobre estas tablas solo ALTER-an.

-- ===================== lineup =====================
create table if not exists public.lineup (
  id             bigint generated by default as identity primary key,
  fecha_consulta date not null,
  port           text not null,
  berth          text,
  vessel         text not null,
  ops            text,
  cat            text,
  cargo          text,
  quantity       integer,
  dest_orig      text,
  area           text,
  shipper        text,
  eta            date,
  etb            date,
  ets            date,
  remarks        text,
  es_agro        boolean default false,
  created_at     timestamptz default now()
);
create unique index if not exists lineup_unique_row on public.lineup
  (fecha_consulta, port, berth, vessel, cargo, quantity, eta, dest_orig, shipper, ops) nulls not distinct;
create index if not exists idx_lineup_fecha  on public.lineup (fecha_consulta);
create index if not exists idx_lineup_cargo  on public.lineup (cargo);
create index if not exists idx_lineup_esagro on public.lineup (es_agro);
create index if not exists idx_lineup_shipper on public.lineup (shipper);

-- ===================== djve =====================
create table if not exists public.djve (
  id                    bigint generated by default as identity primary key,
  anio                  integer not null,
  nro_djve              text,
  fecha_registro        date,
  fecha_presentacion    date,
  producto              text,
  toneladas             numeric,
  fecha_inicio_embarque date,
  fecha_fin_embarque    date,
  opcion                text,
  razon_social          text,
  codigo_interno        text,
  actualizado_en        timestamptz not null default now(),
  cosecha               text
);
create unique index if not exists idx_djve_unique_nro     on public.djve (anio, nro_djve);
create index if not exists        idx_djve_anio           on public.djve (anio);
create index if not exists        idx_djve_codigo         on public.djve (codigo_interno);
create index if not exists        idx_djve_fecha_registro on public.djve (fecha_registro);

-- ===================== compras =====================
-- NOTA: montos en double precision (float8) por herencia; la auditoría E4 evalúa migrarlos a numeric.
create table if not exists public.compras (
  id                  bigint generated by default as identity primary key,
  fecha               date not null,
  grano_raw           text,
  codigo_interno      text not null,
  campana             text not null,
  sector              text not null,
  toneladas           double precision default 0,
  toneladas_a_fijar   double precision,
  precio_promedio_usd double precision,
  porcentaje_cosecha  double precision,
  actualizado_en      timestamptz default now(),
  semanal_tn          double precision,
  precio_hecho_tn     double precision,
  fijado_tn           double precision,
  saldo_a_fijar_tn    double precision,
  djve_tn             double precision,
  fuente              text
);
create unique index if not exists compras_campana_codigo_interno_sector_fecha_key
  on public.compras (campana, codigo_interno, sector, fecha);
create index if not exists compras_codigo_campana_idx on public.compras (codigo_interno, campana);

-- ===================== pizarra_historico =====================
create table if not exists public.pizarra_historico (
  grano          text not null,
  fecha          date not null,
  precio_ars     numeric,
  precio_usd     numeric,
  es_estimativo  boolean not null default false,
  actualizado_en timestamptz not null default now(),
  primary key (grano, fecha)
);
create index if not exists pizarra_historico_fecha_idx on public.pizarra_historico (fecha desc);

-- ===================== cbot_cierres =====================
create table if not exists public.cbot_cierres (
  symbol            text not null,
  fecha             date not null,
  root              text,
  grano             text,
  posicion          text,
  mes               date,
  vencimiento       date,
  settlement_cents  numeric,
  settlement_usd_tn numeric,
  open_cents        numeric,
  high_cents        numeric,
  low_cents         numeric,
  volume            bigint,
  open_interest     bigint,
  actualizado_en    timestamptz not null default now(),
  primary key (symbol, fecha)
);
create index if not exists cbot_cierres_fecha_idx       on public.cbot_cierres (fecha desc);
create index if not exists cbot_cierres_grano_fecha_idx on public.cbot_cierres (grano, fecha desc);

-- ===================== RLS + policies de lectura (estado actual) =====================
-- Todas con lectura pública anon (modelo "todo público" mientras AUTH_ENFORCED está apagado).
-- La visibilidad definitiva (qué queda solo-mesa al prender el login) se resuelve aparte — ver E1 #2.
do $$
begin
  execute 'alter table public.lineup            enable row level security';
  execute 'alter table public.djve              enable row level security';
  execute 'alter table public.compras           enable row level security';
  execute 'alter table public.pizarra_historico enable row level security';
  execute 'alter table public.cbot_cierres      enable row level security';
exception when others then null;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='lineup' and policyname='anon_select_lineup') then
    create policy "anon_select_lineup" on public.lineup for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='djve' and policyname='anon_select_djve') then
    create policy "anon_select_djve" on public.djve for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='compras' and policyname='compras lectura publica') then
    create policy "compras lectura publica" on public.compras for select to public using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='pizarra_historico' and policyname='anon read pizarra_historico') then
    create policy "anon read pizarra_historico" on public.pizarra_historico for select to public using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='cbot_cierres' and policyname='anon read cbot_cierres') then
    create policy "anon read cbot_cierres" on public.cbot_cierres for select to public using (true);
  end if;
end $$;
